language: cpp

matrix:
  include:
    - os: windows
      script: 
        - mkdir build_windows
        - cd build_windows 
        - cmake .. && cmake --build . -- -m
    - os: osx
      osx_image: xcode9.4
      script: 
        - mkdir build_macOS
        - cd build_macOS
        - cmake .. && cmake --build . -- -j2
    - os: linux
      dist: xenial
      compiler: gcc
      script: 
        - mkdir build_linux
        - cd build_linux
        - cmake -DWS=NullWS .. && cmake --build . -- -j2 
    - os: linux
      dist: xenial
      compiler: clang
      script: 
        - mkdir build_linux
        - cd build_linux
        - cmake -DWS=NullWS .. && cmake --build . -- -j2
branches:
  only:
    - master