language: cpp

matrix:
  include:
    - name: "Android"
      os: linux
      dist: trusty
      language: android
      android:
      components:
          - tools
          - platform-tools
          - tools
          - build-tools-29.0.0
          - android-29
      licenses:
          - 'android-sdk-preview-license-.+'
          - 'android-sdk-license-.+'
          - 'android-ndk-license-.+'
      before_install: 
          - echo y | sdkmanager "ndk-bundle"
          - echo y | sdkmanager --channel=3 --channel=1 "cmake;3.10.2.4988404"
      before_script: 
          - cd build-android 
          - chmod +x gradlew
      script: ./gradlew -PANDROID_ABI=arm64-v8a -PNOSIGN assembleRelease --stacktrace
    - name: "Windows 32bit"
      os: windows
      script: 
        - mkdir build_windows_32
        - cd build_windows_32 
        - cmake .. -G"Visual Studio 15 2017" && cmake --build . -- -m
    - name: "Windows 64bit"
      os: windows
      script: 
        - mkdir build_windows_64
        - cd build_windows_64
        - cmake .. -G"Visual Studio 15 2017" -Ax64 && cmake --build . -- -m
    - name: "Linux(Bionic) 32bit - gcc"
      os: linux
      dist: bionic
      compiler: gcc
      before_install:
        - sudo apt-get install gcc-multilib g++-multilib ninja-build
      script: 
        - mkdir build_linux_gcc_32
        - cd build_linux_gcc_32
        - cmake -GNinja -DPVR_WINDOW_SYSTEM=NullWS -DCMAKE_TOOLCHAIN_FILE="../cmake/toolchains/Linux-gcc-x86_32.cmake" .. && cmake --build . -- -j2 
    - name: "Linux(Bionic) 64bit - gcc"
      os: linux
      dist: bionic
      compiler: gcc
      before_install:
        - sudo apt-get install ninja-build
      script: 
        - mkdir build_linux_gcc_64
        - cd build_linux_gcc_64
        - cmake -GNinja -DPVR_WINDOW_SYSTEM=NullWS -DCMAKE_TOOLCHAIN_FILE="../cmake/toolchains/Linux-gcc-x86_64.cmake" .. && cmake --build . -- -j2 
    - name: "Linux(Bionic) - clang"
      os: linux
      dist: bionic
      compiler: clang
      before_install:
        - sudo apt-get install ninja-build
      script: 
        - mkdir build_linux_clang_64
        - cd build_linux_clang_64
        - cmake -GNinja -DPVR_WINDOW_SYSTEM=NullWS .. && cmake --build . -- -j2
    - name: "macOS"
      os: osx
      osx_image: xcode9.4
      script: 
        - mkdir build_macOS
        - cd build_macOS
        - cmake .. && cmake --build . -- -j2
branches:
  only:
    - master
